### ISSUE TITLE
error msg

### ISSUE THREAD

**Issue by genna80** [lminuti/WebStencilsDemo#1]
[dcc32 Fatal Error] Server.Forms.Main.pas(19): F2613 Unit 'WiRL.Core.Engine' not found.

**Comment by genna80** [comment]
in file : Server.Forms.Main

  WiRL.Engine.Core,

**Comment by lminuti** [comment]
**This project is no longer maintained** and is not compatible with recent versions of WiRL. 
The source code is now available in the [WebStencilsDemo](https://github.com/delphi-blocks/WiRL/tree/master/Demos/22.WebStencilsDemo) of the official WiRL repository.
