### ISSUE TITLE
Error after replacing libraries

### ISSUE THREAD

**Issue by genna80** [lminuti/WebStencilsDemo#3]
Ref: https://github.com/lminuti/WebStencilsDemo/issues/2
Ref: https://github.com/lminuti/WebStencilsDemo/issues/1
 
[dcc32 Error] Server.Forms.Main.pas(80): E2250 There is no overloaded version of 'AddEngine' that can be called with these arguments

**Comment by lminuti** [comment]
**This project is no longer maintained** and is not compatible with recent versions of WiRL. 
The source code is now available in the [WebStencilsDemo](https://github.com/delphi-blocks/WiRL/tree/master/Demos/22.WebStencilsDemo) of the official WiRL repository.
